apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: self-healing-platform
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/shantanu23-case/self-healing-platform.git
    targetRevision: HEAD
    path: apps

  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true