apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: healer-config
  namespace: monitoring
spec:
  route:
    receiver: healer

  receivers:
  - name: healer
    webhookConfigs:
    - url: "http://healer-service.demo.svc.cluster.local:5000/heal"